/*
 * default_scene_text.h - the built-in default scene, embedded as text.
 *
 * AUTO-GENERATED from scenes/default.scene. Do not edit by hand:
 * regenerate from that file (keeping the bytes below identical to it).
 *
 * The program works standalone (no scenes/ directory required): src/main.c
 * #includes this header, so DEFAULT_SCENE_TEXT is compiled into the binary,
 * and the no---scene path parses it with scene_desc_load_string() before
 * scene_build_from_desc(). The bytes below are identical to
 * scenes/default.scene, so rendering the built-in default is byte-identical
 * to rendering that file.
 *
 * Header-only: no translation unit, no Makefile registration needed. It is
 * compiled into the binary solely via the #include in src/main.c.
 */

#ifndef RAYTRACER_DEFAULT_SCENE_TEXT_H
#define RAYTRACER_DEFAULT_SCENE_TEXT_H

/* Byte-identical to the contents of scenes/default.scene (ASCII). */
static const char DEFAULT_SCENE_TEXT[] =
    "# scenes/default.scene\n"
    "#\n"
    "# The built-in default scene, expressed in the data-driven scene format\n"
    "# (see docs/scene_format.md). This file is the canonical source for the\n"
    "# default scene: it is byte-for-byte the text embedded in the binary via\n"
    "# src/default_scene_text.h, and its body is exactly what `--write-scene`\n"
    "# emits for the built-in description.\n"
    "#\n"
    "# Rendering this file is byte-identical to the embedded default parsed from\n"
    "# src/default_scene_text.h (verified at 1920x1080/16 spp, 1280x720/16 spp\n"
    "# and 320x180/4 spp, depth 6, seed 1337).\n"
    "\n"
    "water_level = 0.02\n"
    "water_material = water\n"
    "water_enabled = 1\n"
    "\n"
    "camera {\n"
    "    eye = -18 6 22\n"
    "    target = 0 5 -20\n"
    "    up = 0 1 0\n"
    "    vfov = 40\n"
    "}\n"
    "\n"
    "sky {\n"
    "    sun_dir = 0.4466625002869186 0.7444375004781977 -0.4962916669854651\n"
    "    sun_color = 1 0.95 0.85\n"
    "    horizon_color = 0.75 0.85 1\n"
    "    zenith_color = 0.35 0.55 0.95\n"
    "    gradient_gamma = 0.6\n"
    "    sun_glow_exponent = 350\n"
    "    sun_glow_strength = 0.8\n"
    "    cloud_height = 120\n"
    "    cloud_scale = 0.0025\n"
    "    cloud_coverage = 0.5\n"
    "    cloud_softness = 0.12\n"
    "    cloud_sharpness = 1.5\n"
    "    cloud_octaves = 5\n"
    "    seed = 1337\n"
    "}\n"
    "\n"
    "material ground {\n"
    "    albedo = 0.3 0.42 0.16\n"
    "    specular = 0.05 0.05 0.05\n"
    "    shininess = 8\n"
    "    reflectivity = 0\n"
    "    transparency = 0\n"
    "    ior = 1\n"
    "    is_water = 0\n"
    "    absorption = 0 0 0\n"
    "    deep_color = 0 0 0\n"
    "}\n"
    "\n"
    "material bark {\n"
    "    albedo = 0.26 0.18 0.11\n"
    "    specular = 0.04 0.04 0.04\n"
    "    shininess = 6\n"
    "    reflectivity = 0\n"
    "    transparency = 0\n"
    "    ior = 1\n"
    "    is_water = 0\n"
    "    absorption = 0 0 0\n"
    "    deep_color = 0 0 0\n"
    "}\n"
    "\n"
    "material leaf0 {\n"
    "    albedo = 0.16 0.38 0.12\n"
    "    specular = 0.03 0.04 0.03\n"
    "    shininess = 10\n"
    "    reflectivity = 0\n"
    "    transparency = 0\n"
    "    ior = 1\n"
    "    is_water = 0\n"
    "    absorption = 0 0 0\n"
    "    deep_color = 0 0 0\n"
    "}\n"
    "\n"
    "material leaf1 {\n"
    "    albedo = 0.22 0.45 0.15\n"
    "    specular = 0.03 0.04 0.03\n"
    "    shininess = 10\n"
    "    reflectivity = 0\n"
    "    transparency = 0\n"
    "    ior = 1\n"
    "    is_water = 0\n"
    "    absorption = 0 0 0\n"
    "    deep_color = 0 0 0\n"
    "}\n"
    "\n"
    "material leaf2 {\n"
    "    albedo = 0.3 0.5 0.18\n"
    "    specular = 0.03 0.04 0.03\n"
    "    shininess = 10\n"
    "    reflectivity = 0\n"
    "    transparency = 0\n"
    "    ior = 1\n"
    "    is_water = 0\n"
    "    absorption = 0 0 0\n"
    "    deep_color = 0 0 0\n"
    "}\n"
    "\n"
    "material leaf3 {\n"
    "    albedo = 0.12 0.3 0.1\n"
    "    specular = 0.03 0.04 0.03\n"
    "    shininess = 10\n"
    "    reflectivity = 0\n"
    "    transparency = 0\n"
    "    ior = 1\n"
    "    is_water = 0\n"
    "    absorption = 0 0 0\n"
    "    deep_color = 0 0 0\n"
    "}\n"
    "\n"
    "material water {\n"
    "    type = water\n"
    "}\n"
    "\n"
    "plane {\n"
    "    point = 0 0 0\n"
    "    normal = 0 1 0\n"
    "    material = ground\n"
    "}\n"
    "\n"
    "box {\n"
    "    center = 0 -0.009999999999999998 -25\n"
    "    half = 45 0.03 45\n"
    "    material = water\n"
    "}\n"
    "\n"
    "tree {\n"
    "    position = 50 0 -80\n"
    "    height = 3.4\n"
    "    radius = 0.2\n"
    "    seed = 3128892807\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf2\n"
    "    leaf_variant = 2\n"
    "}\n"
    "\n"
    "tree {\n"
    "    position = 30 0 -105\n"
    "    height = 2.8\n"
    "    radius = 0.07\n"
    "    seed = 1448886631\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf2\n"
    "    leaf_variant = 2\n"
    "}\n"
    "\n"
    "tree {\n"
    "    position = -35 0 -100\n"
    "    height = 2.7\n"
    "    radius = 0.07\n"
    "    seed = 1959102491\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf0\n"
    "    leaf_variant = 0\n"
    "}\n"
    "\n"
    "tree {\n"
    "    position = 70 0 -60\n"
    "    height = 2.6\n"
    "    radius = 0.07\n"
    "    seed = 2945246587\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf3\n"
    "    leaf_variant = 3\n"
    "}\n"
    "\n"
    "tree {\n"
    "    position = 15 0 -115\n"
    "    height = 2.2\n"
    "    radius = 0.05\n"
    "    seed = 1816962403\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf3\n"
    "    leaf_variant = 3\n"
    "}\n"
    "\n"
    "tree {\n"
    "    position = -60 0 -85\n"
    "    height = 2.2\n"
    "    radius = 0.05\n"
    "    seed = 4003524602\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf0\n"
    "    leaf_variant = 0\n"
    "}\n"
    "\n"
    "bush {\n"
    "    position = -48 0 -55\n"
    "    height = 0.8\n"
    "    radius = 0.05\n"
    "    seed = 4181885975\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf0\n"
    "    leaf_variant = 0\n"
    "}\n"
    "\n"
    "bush {\n"
    "    position = 55 0 -100\n"
    "    height = 0.7\n"
    "    radius = 0.05\n"
    "    seed = 4072799993\n"
    "    material_bark = bark\n"
    "    material_leaf = leaf2\n"
    "    leaf_variant = 2\n"
    "}\n"
    ;

#endif /* RAYTRACER_DEFAULT_SCENE_TEXT_H */
